// https://opentdb.com/api.php?amount=20&category=21&difficulty=easy&type=multiple   url from come
const questions = [
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which English football club has the nickname &#039;The Foxes&#039;?",
    answer: 1, // It means first index of options array is correct
    options: [
      "Northampton Town",
      "Leicester City",
      "Bradford City",
      "West Bromwich Albion",
    ],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which team won the 2015-16 English Premier League?",
    answer: 1,
    options: ["Liverpool", "Leicester City", "Cheslea", "Manchester United"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "In baseball, how many fouls are an out?",
    answer: 0,
    options: ["0", "5", "3", "2"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "The Rio 2016 Summer Olympics held it&#039;s closing ceremony on what date?",
    answer: 2,
    options: ["August 23", "August 19", "August 21", "August 17"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which country will host the 2020 Summer Olympics?",
    answer: 3,
    options: ["China", "Australia", "Germany", "Japan"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Who won the 2015 Formula 1 World Championship?",
    answer: 1,
    options: [
      "Nico Rosberg",
      "Lewis Hamilton",
      "Sebastian Vettel",
      "Jenson Button",
    ],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "In Baseball, how many times does the ball have to be pitched outside of the strike zone before the batter is walked?",
    answer: 0,
    options: ["4", "1", "2", "3"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which city did the former NHL team &quot;The Nordiques&quot; originiate from?",
    answer: 3,
    options: ["Houston", "Montreal", "New York", "Quebec City"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "What team won the 2016 MLS Cup?",
    answer: 2,
    options: [
      "Colorado Rapids",
      "Toronto FC",
      "Seattle Sounders",
      "Montreal Impact",
    ],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "What year did the New Orleans Saints win the Super Bowl?",
    answer: 0,
    options: ["2010", "2008", "2009", "2011"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "This Canadian television sportscaster is known for his &quot;Hockey Night in Canada&quot; role, a commentary show during hockey games.",
    answer: 3,
    options: ["Don McKellar", "Don Taylor ", "Donald Sutherland", "Don Cherry"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which team has won the most Stanley Cups in the NHL?",
    answer: 1,
    options: [
      "Chicago Blackhawks",
      "Montreal Canadians",
      "Toronto Maple Leafs",
      "Detroit Red Wings",
    ],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which boxer was banned for taking a bite out of Evander Holyfield&#039;s ear in 1997?",
    answer: 0,
    options: [
      "Mike Tyson",
      "Roy Jones Jr.",
      "Evander Holyfield",
      "Lennox Lewis",
    ],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "What is the most common type of pitch thrown by pitchers in baseball?",
    answer: 2,
    options: ["Slowball", "Screwball", "Fastball", "Palmball"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "What team did England beat to win in the 1966 World Cup final?",
    answer: 3,
    options: ["Soviet Union", "Portugal", "Brazil", "West Germany"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which player holds the NHL record of 2,857 points?",
    answer: 1,
    options: [
      "Mario Lemieux ",
      "Wayne Gretzky",
      "Sidney Crosby",
      "Gordie Howe",
    ],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Who did Steven Gerrard win the Champions League with?",
    answer: 0,
    options: ["Liverpool", "Real Madrid", "Chelsea", "Man City"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question:
      "&quot;Stadium of Light&quot; is the home stadium for which soccer team?",
    answer: 3,
    options: [
      "Barcelona FC",
      "Paris Saints-Germain",
      "Manchester United",
      "Sunderland FC",
    ],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Which country will host the 2022 FIFA World Cup?",
    answer: 2,
    options: ["USA", "Japan", "Qatar", "Switzerland"],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "easy",
    question: "Who won the 2017 Formula One World Drivers&#039; Championship?",
    answer: 0,
    options: [
      "Lewis Hamilton",
      "Sebastian Vettel",
      "Nico Rosberg",
      "Max Verstappen",
    ],
  },
];
